### ISSUE TITLE
Compatiblity with Laravel 8

### ISSUE THREAD

**Issue by rimace** [typehints/laravel-unused#15]
Please release a version that is compatible with Laravel 8.
The current version 0.1.1 required illuminate/filesystem 5.6.*|5.7.*|5.8.*|^6.0|^7.0, but I have 8 installed.

**Comment by volkv** [comment]
+

**Comment by simoebenhida** [comment]
Sorry for the delay! The last version v0.1.2 should support laravel 8

**Comment by volkv** [comment]
@simoebenhida thanks for answer. I see your commit. But it looks like that release version did not receive the last update. Its still ends with `^7.0`
![image](https://user-images.githubusercontent.com/14368228/108538544-f6e6c080-72ef-11eb-8546-03cdfaaa6f71.png)

**Comment by volkv** [comment]
Also I see this block is not used.
![image](https://user-images.githubusercontent.com/14368228/108539678-5e514000-72f1-11eb-81f9-381b9db83f89.png)
 Is it in todo status? :)

**Comment by simoebenhida** [comment]
Yeah that property is not used yet! You should get the last version now
