### ISSUE TITLE
Idea: create a console command that will return a list of unused views

### ISSUE THREAD

**Issue by alies-dev** [typehints/laravel-unused#4]
A separate view is a good option, but a dedicated console command can be integrated to CI pipelines and thus we can catch unused views earlier

**Comment by simoebenhida** [comment]
@lptn Great idea! But I'm worried about the case when people use the name of a view as a variable like `view($usedView)`! The package will not detect those cases and your CI will always fail!

**Comment by alies-dev** [comment]
@simoebenhida 
in a config we can specify ignore pattern(s) for such cases for solve this problem

**Comment by simoebenhida** [comment]
@lptn Oh yeah we can add an array of ignored views! That will surely do it!
Thanks for the feedback!
